default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password

development:
  <<: *default
  database: flashcards_database_development

test:
  <<: *default
  database: flashcards_database_test

production:
  <<: *default  
  database: flashcards_database_production
